### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by mochaojie** [khurramHashmi/Table-detection-Mask_RCNN#1]
What should i do to set the structure of the file when i want to solve the problem about path of the file

**Comment by khurramHashmi** [comment]
Hello Mochaojie,

Go to the table.py script and change the following two functions according to your dataset :
1- load_table
2- load_mask.

Make a CSV or JSON file as you prefer. You can also visualize your data using the inspect_table_data.ipynb script to see whether the data is properly loaded or not.

**Comment by mochaojie** [comment]
thank for your answer.  while I can't download mask_rcnn_table_0050.h5 successfully maybe I am in china.  I hope you can transfer for me through e-mail. thank you very much. ------------------ 原始邮件 ------------------
发件人: "khurramHashmi"<notifications@github.com>
发送时间: 2019年9月23日(星期一) 晚上9:00
收件人: "khurramHashmi/Table-detection-Mask_RCNN"<Table-detection-Mask_RCNN@noreply.github.com>;
抄送: "mochaojie"<810375129@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [khurramHashmi/Table-detection-Mask_RCNN] how to run it (#1)



Hello Mochaojie,
 
Go to the table.py script and change the following two functions according to your dataset :
 1- load_table
 2- load_mask.
 
Make a CSV or JSON file as you prefer. You can also visualize your data using the inspect_table_data.ipynb script to see whether the data is properly loaded or not.
 
&mdash;

**Comment by khurramHashmi** [comment]
Sorry, it's not possible to share the model at the moment. However, with the help of the given scripts, you can train one. I'll share the model on the mentioned email when I can :)
